INSERT INTO udogodnienia (udogodnienie)
VALUES ('garaż'),
       ('kuchnia otwarta'),
       ('pralka'),
       ('zmywarka'),
       ('winda'),
       ('klimatyzacja'),
       ('kanalizacja'),
       ('szambo'),
       ('wodociąg'),
       ('gaz'),
       ('prąd'),
       ('kominek'),
       ('spiżarnia'),
       ('ogród'),
       ('balkon');
